before_install:  # Earliest build step
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo "Not a PR, skipping" && exit; fi

language: ruby

cache: bundler

rvm:
 - 2.3

install:
  - bundle install

script:
  - ./bin/lint.sh
